# Generated by Django 4.2 on 2023-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_api', '0002_monstercard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monstercard',
            name='type',
            field=models.CharField(max_length=90),
        ),
    ]
